version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '54320:5432'
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: 2@2.com
      PGADMIN_DEFAULT_PASSWORD: admin
      POSTGRES_DB: drips
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - '5050:80'
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
